'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('lote', [{
      numeroLote: 1,
      descricao: 'Lote de ouro coletado da Montanha Solitária',
      quantidade: 1000,
      valorInicial: 100000.00,
      unidade: 4,
      leilao: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      numeroLote: 1,
      descricao: 'O Um Anel',
      quantidade: 1,
      valorInicial: 10000000.00,
      unidade: 1,
      leilao: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      numeroLote: 1,
      descricao: 'Espada Ferroada',
      quantidade: 1,
      valorInicial: 10000.00,
      unidade: 1,
      leilao: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      numeroLote: 1,
      descricao: 'Malha de Mithril',
      quantidade: 1,
      valorInicial: 10000.00,
      unidade: 1,
      leilao: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      numeroLote: 1,
      descricao: 'Lembas',
      quantidade: 10,
      valorInicial: 10.00,
      unidade: 3,
      leilao: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      numeroLote: 1,
      descricao: 'Mobilha',
      quantidade: 1,
      valorInicial: 1000.00,
      unidade: 1,
      leilao: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      numeroLote: 2,
      descricao: 'Ponei',
      quantidade: 1,
      valorInicial: 100.00,
      unidade: 1,
      leilao: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      numeroLote: 2,
      descricao: 'Carroça',
      quantidade: 1,
      valorInicial: 100.00,
      unidade: 1,
      leilao: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      numeroLote: 4,
      descricao: 'Casa na vila dos Hobbits',
      quantidade: 1,
      valorInicial: 10000.00,
      unidade: 1,
      leilao: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      numeroLote: 1,
      descricao: 'Espda Anduril',
      quantidade: 1,
      valorInicial: 10000.00,
      unidade: 1,
      leilao: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      numeroLote: 1,
      descricao: 'Arco Élfico',
      quantidade: 1,
      valorInicial: 10000.00,
      unidade: 1,
      leilao: 6,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      numeroLote: 1,
      descricao: 'Machado de Batalha',
      quantidade: 1,
      valorInicial: 10000.00,
      unidade: 1,
      leilao: 7,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      numeroLote: 1,
      descricao: 'Armadura Élfica',
      quantidade: 1,
      valorInicial: 100000.00,
      unidade: 1,
      leilao: 8,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      numeroLote: 1,
      descricao: 'Armadura Anão',
      quantidade: 1,
      valorInicial: 100000.00,
      unidade: 1,
      leilao: 9,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      numeroLote: 1,
      descricao: 'Espada curta',
      quantidade: 1,
      valorInicial: 1000.00,
      unidade: 1,
      leilao: 10,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('lote', null, {});
  }
};
